using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pole : MonoBehaviour
{
    [Tooltip("The points on this pole where wires will connect. If empty, the system will try to auto-detect child GameObjects with 'connector' in their name.")]
    public Transform[] connectors;

    private void Awake()
    {
        AutoDetectConnectors();
    }

    /// <summary>
    /// Attempts to find connectors if none are assigned.
    /// First looks for children containing 'connector' in their name.
    /// If none are found, creates a default connector at the top of the model's bounds.
    /// </summary>
    public void AutoDetectConnectors()
    {
        if (connectors != null && connectors.Length > 0)
        {
            // Connectors are already manually assigned
            return;
        }

        // Search for children with "connector" in their name
        List<Transform> foundConnectors = new List<Transform>();
        Transform[] allChildren = GetComponentsInChildren<Transform>(true);

        foreach (Transform child in allChildren)
        {
            // Skip the root transform of this Pole GameObject
            if (child == transform) continue;

            if (child.name.ToLower().Contains("connector"))
            {
                foundConnectors.Add(child);
            }
        }

        if (foundConnectors.Count > 0)
        {
            connectors = foundConnectors.ToArray();
            Debug.Log($"[Pole] Auto-detected {connectors.Length} connector(s) in child objects of '{gameObject.name}'", gameObject);
            return;
        }

        // Fallback: Calculate the top center of the model and create a default connector there
        Vector3 topPos = GetTopCenterPosition();
        
        // Create a new child GameObject to act as the connector
        GameObject defaultConnectorObj = new GameObject("Connector_Default_AutoGenerated");
        defaultConnectorObj.transform.SetParent(transform);
        defaultConnectorObj.transform.position = topPos;
        defaultConnectorObj.transform.localRotation = Quaternion.identity;

        connectors = new Transform[] { defaultConnectorObj.transform };
        Debug.LogWarning($"[Pole] No connectors found in '{gameObject.name}'. Auto-generated a default connector at the top of the bounds.", gameObject);
    }

    /// <summary>
    /// Calculates the top center position of this GameObject using its Renderers.
    /// </summary>
    private Vector3 GetTopCenterPosition()
    {
        Renderer[] renderers = GetComponentsInChildren<Renderer>();
        if (renderers.Length == 0)
        {
            // Default to 5 units high if there is no renderer
            return transform.position + Vector3.up * 5.0f;
        }

        Bounds combinedBounds = renderers[0].bounds;
        for (int i = 1; i < renderers.Length; i++)
        {
            combinedBounds.Encapsulate(renderers[i].bounds);
        }

        // Return top center
        return new Vector3(combinedBounds.center.x, combinedBounds.max.y, combinedBounds.center.z);
    }

    /// <summary>
    /// Returns the connector at the specified index, wrapping around or returning the main transform if out of range.
    /// </summary>
    public Transform GetConnector(int index)
    {
        if (connectors == null || connectors.Length == 0)
        {
            return transform;
        }

        // Safety: If index is out of bounds, wrap or clamp it
        int safeIndex = Mathf.Clamp(index, 0, connectors.Length - 1);
        return connectors[safeIndex];
    }
}